export type Flashcard = { front: string; back: string };
export type Deck = { id: string; title: string; topic: string; difficulty: "Beginner" | "Intermediate" | "Advanced"; cards: Flashcard[]; lastScore?: number };

export const DECKS: Deck[] = [
    {
        id: "1",
        title: "Sorting Algorithms",
        topic: "COMP201",
        difficulty: "Intermediate",
        cards: [
            { front: "What is the time complexity of Merge Sort?", back: "O(n log n) in all cases — best, average, and worst." },
            { front: "Is Quick Sort a stable sort?", back: "No. Quick Sort is not stable by default, as equal elements may be reordered." },
            { front: "What data structure does Heap Sort use?", back: "A max-heap (binary heap), which guarantees O(n log n) time." },
            { front: "When is Insertion Sort faster than Merge Sort?", back: "On small or nearly-sorted arrays (n ≤ ~20), due to lower constant overhead." },
            { front: "What is the best case for Bubble Sort?", back: "O(n) — when the array is already sorted and an optimised flag is used." },
        ],
    },
    {
        id: "2",
        title: "Binary Trees",
        topic: "COMP201",
        difficulty: "Advanced",
        cards: [
            { front: "What is an in-order traversal?", back: "Left → Root → Right. Produces sorted output on a BST." },
            { front: "What is the height of a balanced BST with n nodes?", back: "O(log n)." },
            { front: "What makes a tree a Binary Search Tree (BST)?", back: "For every node: all left descendants < node < all right descendants." },
            { front: "What traversal is used to copy a tree?", back: "Pre-order (Root → Left → Right)." },
        ],
    },
    {
        id: "3",
        title: "Data Structures",
        topic: "COMP201",
        difficulty: "Beginner",
        cards: [
            { front: "Average time complexity for hash table lookup?", back: "O(1) — constant time, assuming a good hash function and low load factor." },
            { front: "What is a linked list's access time?", back: "O(n) — must traverse from the head to reach a specific index." },
            { front: "What problem does a hash collision cause?", back: "Two keys map to the same bucket. Resolved by chaining or open addressing." },
        ],
    },
    {
        id: "4",
        title: "React Hooks",
        topic: "Web Development",
        difficulty: "Intermediate",
        cards: [
            { front: "What does useState return?", back: "A tuple: the current state value and a setter function." },
            { front: "When does useEffect run?", back: "After every render by default; controlled by its dependency array." },
            { front: "What is the purpose of useCallback?", back: "Memoizes a function so it isn't recreated on every render." },
            { front: "What does useRef return?", back: "A mutable ref object whose .current property persists across renders without triggering re-renders." },
            { front: "What is the difference between useMemo and useCallback?", back: "useMemo memoizes a computed value; useCallback memoizes a function reference." },
            { front: "When would you use useReducer over useState?", back: "When state transitions are complex or the next state depends on the previous." },
        ],
    },
    {
        id: "5",
        title: "TypeScript Generics",
        topic: "Programming",
        difficulty: "Advanced",
        cards: [
            { front: "What is a generic in TypeScript?", back: "A placeholder type that lets you write reusable components without sacrificing type safety." },
            { front: "What does `T extends object` mean?", back: "It constrains T so only object types are accepted, not primitives." },
            { front: "What is the `keyof` operator?", back: "Produces a union of all known property keys of a type." },
            { front: "What does `Partial<T>` do?", back: "Makes all properties of T optional." },
            { front: "What does `Required<T>` do?", back: "Makes all properties of T required, removing any optional modifiers." },
            { front: "What is `ReturnType<T>`?", back: "A utility type that extracts the return type of a function type T." },
        ],
    },
    {
        id: "6",
        title: "CSS Flexbox",
        topic: "Web Design",
        difficulty: "Beginner",
        cards: [
            { front: "What property turns an element into a flex container?", back: "`display: flex`" },
            { front: "What does `justify-content` control?", back: "Alignment of flex items along the main axis." },
            { front: "What does `align-items` control?", back: "Alignment of flex items along the cross axis." },
            { front: "What does `flex-wrap: wrap` do?", back: "Allows flex items to wrap onto multiple lines instead of overflowing." },
            { front: "What is the default value of `flex-direction`?", back: "`row` — items are placed left to right." },
        ],
    },
    {
        id: "7",
        title: "HTTP & REST",
        topic: "Web Development",
        difficulty: "Beginner",
        cards: [
            { front: "What does a 404 status code mean?", back: "Not Found — the requested resource does not exist on the server." },
            { front: "What is the difference between PUT and PATCH?", back: "PUT replaces the entire resource; PATCH applies a partial update." },
            { front: "What does idempotent mean in HTTP?", back: "Making the same request multiple times has the same effect as making it once." },
            { front: "What is CORS?", back: "Cross-Origin Resource Sharing — a browser mechanism that restricts cross-origin HTTP requests." },
            { front: "Which HTTP method is used to retrieve a resource?", back: "GET" },
        ],
    },
    {
        id: "8",
        title: "SQL Fundamentals",
        topic: "Databases",
        difficulty: "Beginner",
        cards: [
            { front: "What does `SELECT DISTINCT` do?", back: "Returns only unique values, removing duplicate rows." },
            { front: "What is a PRIMARY KEY?", back: "A column (or set of columns) that uniquely identifies each row in a table." },
            { front: "What is a FOREIGN KEY?", back: "A column that references the primary key of another table to enforce referential integrity." },
            { front: "What does `GROUP BY` do?", back: "Groups rows that share a value so aggregate functions can be applied per group." },
            { front: "What is the difference between WHERE and HAVING?", back: "WHERE filters rows before aggregation; HAVING filters groups after aggregation." },
            { front: "What does an INNER JOIN return?", back: "Only rows where there is a match in both tables." },
        ],
    },
    {
        id: "9",
        title: "Python Data Structures",
        topic: "Data Science",
        difficulty: "Intermediate",
        cards: [
            { front: "What is the time complexity of Python list append?", back: "Amortised O(1)." },
            { front: "What is the difference between a list and a tuple?", back: "Lists are mutable; tuples are immutable." },
            { front: "How does a Python dict maintain insertion order?", back: "Since Python 3.7, dicts are implemented as ordered hash maps." },
            { front: "What is a Python set?", back: "An unordered collection of unique elements backed by a hash table." },
            { front: "What does `defaultdict` do?", back: "Returns a default value instead of raising KeyError when a key is missing." },
        ],
    },
    {
        id: "10",
        title: "Git Essentials",
        topic: "DevOps",
        difficulty: "Beginner",
        cards: [
            { front: "What does `git rebase` do?", back: "Moves or replays commits onto a new base commit, rewriting history." },
            { front: "What is the difference between merge and rebase?", back: "Merge preserves full history with a merge commit; rebase creates a linear history." },
            { front: "What does `git stash` do?", back: "Temporarily shelves uncommitted changes so you can switch context." },
            { front: "What does `git cherry-pick` do?", back: "Applies a specific commit from another branch onto the current branch." },
            { front: "What is a detached HEAD?", back: "A state where HEAD points directly to a commit rather than a branch reference." },
        ],
    },
    {
        id: "11",
        title: "Operating Systems",
        topic: "COMP301",
        difficulty: "Advanced",
        cards: [
            { front: "What is a deadlock?", back: "A situation where two or more processes are each waiting for resources held by the others, so none can proceed." },
            { front: "What are the four Coffman conditions for deadlock?", back: "Mutual exclusion, hold and wait, no preemption, and circular wait." },
            { front: "What is virtual memory?", back: "An abstraction that gives each process the illusion of a large, contiguous address space by mapping to physical memory and disk." },
            { front: "What is the difference between a process and a thread?", back: "Threads share the same memory space; processes have separate address spaces." },
            { front: "What does the scheduler do?", back: "Decides which process or thread runs on the CPU at any given time." },
        ],
    },
    {
        id: "12",
        title: "Networking Basics",
        topic: "COMP301",
        difficulty: "Intermediate",
        cards: [
            { front: "What is the difference between TCP and UDP?", back: "TCP is reliable and ordered; UDP is faster but offers no delivery guarantees." },
            { front: "What is a subnet mask?", back: "A 32-bit number that divides an IP address into network and host portions." },
            { front: "What does DNS do?", back: "Resolves human-readable domain names to IP addresses." },
            { front: "What is the OSI model?", back: "A 7-layer conceptual framework: Physical, Data Link, Network, Transport, Session, Presentation, Application." },
            { front: "What port does HTTPS use by default?", back: "Port 443." },
            { front: "What is ARP?", back: "Address Resolution Protocol — maps an IP address to a MAC address on a local network." },
        ],
    },
]
